### ISSUE TITLE
vedirect cannot open serial interface

### ISSUE THREAD

**Issue by decodeais** [iuriaranda/venus-docker#1]
Hello,
I was looking for a possibility to use  nodered with a victron solar charger without an additional VenusOS Raspi.
Your solution would be a easy workaround, I thought. 
The problem is I have  no experience with docker. I got the 'allinone' container running, but the 'vedirect' stops with this error on the serial interface. 
```
pi@raspberrypi:~/venus-docker-main $ ls -l /dev/serial/by-id/
insgesamt 0
lrwxrwxrwx 1 root root 13 11. Jan 19:42 usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0 -> ../../ttyUSB0
```

```
pi@raspberrypi:~/venus-docker-main $ docker run vedirect
vedirect-dbus 3.70
000.000 ERR.serial: could not open com-port
000.000 INF.task: done in 000.000``
```
I hope it's just a silly mistake on my part. It would be nice if you could give me a hint.

**Comment by decodeais** [comment]
Now it is working. somthing must have been wrong.

**Comment by digitalwm** [comment]
Got the same issue, did you do anything to fix it?

**Comment by decodeais** [comment]
Sorry, I have no idea. Now I decided to read the values with a esp32/Arduino via VE.direct and send it direct to a InfluxDB Server.
There I don't need a Raspberry anymore. The advantage is that its much cheaper, saves power and you need no USB/RS232 Adapter.

**Comment by iuriaranda** [comment]
Sorry for the late reply.

The `allinone` Docker image is still a work in progress, and tbh I haven't tested it myself. Since I consider that a distributed setup with containers for each service is a better approach, I think I'll just remove it from the repo.

Also, and might be related to the problem you were having, I've noticed that there was a mistake in the documentation about the `VEDIRECTDEV` environment variable. It should be set to the full path of the USB device inside the container, not just the file name like it was mentioned in the documentation. I've fixed it in a recent commit: https://github.com/iuriaranda/venus-docker/commit/f545f5f1dd05cae0744eefcac8abdfa19fdf7be1

@digitalwm if you're also having issues with the `allinone` image, I suggest you give the other individual images a try.

**Comment by decodeais** [comment]
Thank you for for your reply, but after this problems I decided to read the VEdirect by an cheap Arduino and send the data to an InfluxDB Database. May be I will try that containers solution later.

**Comment by ersingencturk** [comment]
> Sorry, I have no idea. Now I decided to read the values with a esp32/Arduino via VE.direct and send it direct to a InfluxDB Server. There I don't need a Raspberry anymore. The advantage is that its much cheaper, saves power and you need no USB/RS232 Adapter.

sorry, unrelated but were you able to feed the power directly from mppt vedirect port  itself or do you use seperate power source?

**Comment by decodeais** [comment]
The  5V output current of the MPPT are only a few mA. A Great advantage of the used ESP32 controler is that it has a much more stable WiFi connection. The RPI4 has a great bug with its WLAN.I use the battery voltage with a 5V buck converter. When I'm back home I will measure the real powere consumption.Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Ersin ***@***.***> Datum: 07.03.23  19:39  (GMT+01:00) An: iuriaranda/venus-docker ***@***.***> Cc: decodeais ***@***.***>, State change ***@***.***> Betreff: Re: [iuriaranda/venus-docker] vedirect cannot open serial interface (Issue #1) 

Sorry, I have no idea. Now I decided to read the values with a esp32/Arduino via VE.direct and send it direct to a InfluxDB Server. There I don't need a Raspberry anymore. The advantage is that its much cheaper, saves power and you need no USB/RS232 Adapter.

sorry, unrelated but were you able to feed the power directly from mppt vedirect port  itself or do you use seperate power source?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/iuriaranda/venus-docker/issues/1#issuecomment-1458649898",
"url": "https://github.com/iuriaranda/venus-docker/issues/1#issuecomment-1458649898",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
