### ISSUE TITLE
mqtt empty

### ISSUE THREAD

**Issue by disaster123** [iuriaranda/venus-docker#6]
I'm not sure whats wrong - but i only get the serial numbers via MQTT.

The whole MQTT seems to be empty except for the serial numbers...

**Comment by iuriaranda** [comment]
Victron's dbus-mqtt implementation has a keep-alive mechanism. You basically need to send a keep-alive message to the MQTT broker every 30 seconds, and optionally specify the topic paths you want to get messages from. That's just an optimization feature to avoid sending unnecessary traffic through the MQTT network.

You can read more about how that works and how to use it in the Victron's repository: https://github.com/victronenergy/dbus-mqtt

**Comment by iuriaranda** [comment]
I'm going to close this issue as I feel it's a usage question and out of scope of this repo. Feel free to re-open if you feel otherwise
